<?php

/**
 * @file
 * Adds an rule event for when a user account is blocked or unblocked.
 */

/**
 * Implements hook_user_update().
 */
function rules_block_user_user_update($account) {
  // The original user object.
  $original = $account->original;

  if (isset($account->status) && $original->status == 1 && $account->status == 0) {
    // The user account has been blocked.
    rules_invoke_event('user_was_blocked', $account);
  }
  elseif (isset($account->status) && $original->status == 0 && $account->status == 1) {
    // The user account has been unblocked.
    rules_invoke_event('user_was_unblocked', $account);
  }
}

/**
 * Implements hook_rules_event_info().
 */
function rules_block_user_rules_event_info() {
  // User account was blocked.
  $items['user_was_blocked'] = array(
    'label' => t('After blocking a user account'),
    'group' => t('User account'),
    'module' => 'rules_block_user',
    'variables' => array(
      'account' => array(
        'type' => 'user',
        'label' => t('updated user account'),
      ),
    ),
  );

  // User account was unblocked.
  $items['user_was_unblocked'] = array(
    'label' => t('After unblocking a user account'),
    'group' => t('User account'),
    'module' => 'rules_block_user',
    'variables' => array(
      'account' => array(
        'type' => 'user',
        'label' => t('updated user account'),
      ),
    ),
  );

  return $items;
}
